# main menu
main:
  - name: About
    pageRef: /about
    weight: 10
    params:
      icon: about
  
  - name: Resume
    pageRef: /resume
    weight: 20
    params:
      icon: file-text

  - name: More
    weight: 30

  - name: Categories
    weight: 1
    pageRef: /categories
    parent: More
    params:
      icon: categories

  - name: Tags
    weight: 2
    pageRef: /tags
    parent: More
    params:
      icon: tags
  
  - name: Projects
    weight: 3
    pageRef: /projects
    parent: More
    params:
      icon: projects

  # - name: Series
  #   weight: 4
  #   pageRef: /series
  #   parent: More
  #   params:
  #     icon: bookmark


# footer menu
footer:
  - name: Posts
    pageRef: /posts
    weight: 10
    params:
      icon: posts

  - name: Archives
    pageRef: /archives
    weight: 15
    params:
      icon: archive

  - name: RSS Feed
    url: /index.xml
    weight: 20
    params:
      icon: rss

# footer social link
social:
  - name: GitHub
    url: https://github.com/nozhana
    weight: 10
    params:
      icon: github
  - name: Twitter
    url: https://x.com/get__swifty
    weight: 20
    params:
      icon: twitter
  - name: LinkedIn
    url: https://linkedin.com/in/nozhana
    weight: 30
    params:
      icon: linkedin
  - name: Email
    url: mailto:nozhan.work@gmail.com
    weight: 40
    params:
      icon: email
